resources:
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml
