apiVersion: v1
kind: Pod
metadata:
  name: ddns
spec:
  containers:
  - name: ddns
    image: tarikx/digitalocean-ddns:v2
    env:
    - name: DOMAIN
      value: rikb.de
    - name: DIGITALOCEAN_TOKEN
      valueFrom:
        secretKeyRef:
          name: digitalocean
          key: token
