---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: digitalocean
spec:
  encryptedData:
    token: AgB8QkffVWdaq0UTclOHUnK6jTVsYjw09oi3KWytJcVvnJeKIsTQq0FP4AlZaL3l9lEe0B53prG301nWIWd1ABNphplh8Pqjfnkn0mU7foGk7TGD2f48O4j58N6Ag8gr1mMgvyAZMY6pi5Veq9wdMvlZNNgHtJOv62mbaPb+DqfqPpfnjnNaWWHArr6N89OgS+UaZRePFCGMlS5BrsN/VBMhOESEcq6ycn2XarS9B7NtA8XX2WFvQdJtqm6cLPXQzxHvLXMzSo1mpN5HgfILNlC0X1E3Xzc0m+5O1QqvRuSaSwcemYCdHfvVefhF+sNVu57dKRr8LeRhXhusjougYcWCYK8Lc1SmwY9DIH87HCo/4SBKuHWA0541M71geHISXCg+jDpVV2qhiRi2OEMSzACHsb4OySWf9kh3QHcKElEl4gUaTfdwZJodIUP5uPaCF2njHKUqtu8occmYQ8OL/jX+A0mQywTeFXSe9gq90FnMsQkPS7hIvlfuuDSd5+mM4asElKOjHQAj5NjsZvR2J5B40c7M3rCuljC1x0/mrz2MnHP6fn6+w9KmT7/wyp1Gmdi39nR0yg6/2yipYi2OMx32j0oFjuPtbtt6Ps2+PPELql0ubrc65X4rbMGzvBSikIkM1Vqa+HDYdTL/wlGLC2kv3hMPA7xpZqJ7CcXkmvMwVm3b7uNpRSgfjVRWO1WMLAa0vFvMANYBxzacso5YioBoQUxnxKX19w+GzfKqOtws4G1ThOm5SiQiKpz4oEneYidhNcnqgYW/I4+HGgI5yASL/p6UYyLugg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: digitalocean
