---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: digitalocean
spec:
  encryptedData:
    token: AgAWLZvwS1OFWWGeq9yaB2SwYxWJ+1hcOJPqQj995mmcjgJjVUJU/hEsBDxOWT+6yKMWR79bbxQg/wHI//X0QC9bmyczJw8RQNCS8iWv4RMz2twhF6fSWUfJUUMBhvV0m7IUBOPIGMucPj0cdqC5rYXjaqKBc+zUTV2fliFDzCI2PHoChasAcb11D+jCpyzLIzoMpp8dUEwm5lPz60CJPz1uh854SHloJ5tFIh5svaMuGbIG5U+ZJ7G6++rtHpVM16Fv45+QkGLRw9ENCghgZycSyUjqx+7IXtr9E4ojgBrNgaimXib2iTO00y3vAKtc4mrDluthD3hfOxI9kW0wIR7sPqb9kaY9to+t9NufMWbahBtubcibfstVSA+GiXXAQi/wwvi5MokIXJGQsRlsHXjyGTaASRds/b8GHPkaxTbR8Ti1Mow0qjEjiDg3qFhLLGnF5GmjBirBNNiJzMuuQJTKRezrJeu8WqjDJRHqPKsntyHp8WEJ7Hkcfsb1e/0VPFaWeey/hJWDUX6owRJfEScTwewNaX/yHP3g2tJQR2w9TzCEqBlRGCcoDxyPOgAkQtFlSRI72koQHSKlKn3W1Wd0GI3Xo4ZVNakn2zdYj7SmgBtbNz0YsAozMj11xUUTE6OyRSief1fBd2g1ecbYX/PkXlN6strc1zbLYE2sLYprMu/ILN9+BzsjjR1ETW19INPQVaWYat+9Fz8SH+LoLESoIwwuFO1l6DlRRfUChnKGj20Ub2zcmYtv84zC5CG1TSSqqhI09tCQT118zEZD0HW47TVxerRqqA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: digitalocean
