---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean
  namespace: default
spec:
  encryptedData:
    token: AgB1nMdqvuuLReXMb+xYy1TCQ/YWZaoPG8lJsUbWv4QzDJvKFYHjaKg4DbVQDSrOhqMVNtacmU9Yn+08eI3xdH26pEcEewyxmkCFlB/t89HKA49V98UVQ2XhEmYvrzRDhMeLEI9kLcKtThtLIHOnvedCaZGKR7shTdnf7UleSmo0svWTh1rg0ZiuD2qMcH8sL+fDvRkDjOc0HoFX7Maw1fDUboFT38XyrVs5dZtpBm8A0dgyRiOKa0BOf8VcdWTRB3RQquN12ZsoaA+UbnVfgcamve8V0l5hpOR7FwKBK1AtFLz0QrsWgLxD8csWmUwdq0wZ7gg4m9agWR+o1oBSReBNhb6ibJAvFSsV83ZDjrM+aUWOY0Rp+teAl19aqF1FAcuAkcTUcmclmSLAifWxLmi06GX/e1JP9CqKOwtusN/TPkSazbx90KCRpHKCPEJ79n56jBAfkhxsOSy3K0KhXwbD+MnZnbVs0IB83EauOcS1+J0S23jO6owuGNSHi4D4Kq+mu4Ev3EFEk92MptYoeDUudZ3Ppj8MfDGUnYD0LBZK30P7e5+FQDcd2DiEzkd0CKA7w4KiAEznSHDmfgW0TYHYRWgyRnwdXUO8eqlxYrNxy4I5qYU7bOsK0wpHrOGqbARNCzZtsBQFAFa3PbSWsr4ElCAWFqX2sJgEGKCYRLwMSVXtc4xsG4AwgOwHMkB7D+EHld/Zbzn+JN/JqbQebOz6JE+Ra1GlRi/1j4Tko9rCxyD/uYujSaK8puf2zz1kTxmHwuezGeC50B1p8dD0/4RU06SNN5G3bw==
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean
      namespace: default
