apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: flink-kubernetes-operator
    repoURL: https://archive.apache.org/dist/flink/flink-kubernetes-operator-1.9.0
    targetRevision: 1.9.0
  destination:
    namespace: flink
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
