apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argo-events
spec:
  project: default
  source:
    repoURL: "https://github.com/t-arik/homelab"
    targetRevision: main
    path: argocd/argo-events
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
