apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.4
    helm:
      valuesObject:
        provider:
          name: digitalocean
        env:
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: do-token
                key: DO_TOKEN
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
