apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.0.0
    helm:
      valuesObject:
        adminUser: admin
        adminPassword: admin
        persistence:
          enabled: true
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - monitoring.rikb.de
          tls:
            - hosts:
              - monitoring.rikb.de
              secretName: tls-secret
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
