apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/t-arik/homelab"
    targetRevision: main
    path: argocd/guestbook
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

