apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  source:
    chart: plex-media-server
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: 0.4.0
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: nginx
          url: plex.rikb.de
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
